name: release

on:
  push:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.52.0-noble
    env:
      STORYBOOK_URL: https://evlmaistrenko.github.io/js-lib-sandbox/${{ github.sha }}/storybook
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: latest
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm i -D @rollup/rollup-linux-x64-gnu
      - run: npm run test:docs
      - uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.RELEASE_TOKEN }}
          publish_dir: ./docs/test
          destination_dir: ${{ github.sha }}
          keep_files: true
      - run: npx -y wait-on https://evlmaistrenko.github.io/js-lib-sandbox/${{ github.sha }}/storybook && npm test

  release-please:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.RELEASE_TOKEN }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
