name: release

on:
  push:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.52.0-noble
    env:
      STORYBOOK_URL: https://evlmaistrenko.github.io/js-lib-sandbox/${{ github.sha }}/storybook
    steps:
      - name: Get pull request
        id: pr
        uses: actions/github-script@v7
        with:
          script: |
            const commitSha = context.sha;
            const associatedPRs = await github.rest.repos.listPullRequestsAssociatedWithCommit({
              owner: context.repo.owner,
              repo: context.repo.repo,
              commit_sha: commitSha,
            });
            const pr = associatedPRs.data.find(pr => pr.merged_at);
            if (pr) {
              const hasReleaseLabel = pr.labels.some(label => label.name === 'release');
              core.setOutput('skip', hasReleaseLabel);
            } else {
              core.setOutput('skip', false);
            }

      - uses: actions/checkout@v4
        if: steps.pr.outputs.skip != 'true'

      - uses: actions/setup-node@v4
        if: steps.pr.outputs.skip != 'true'
        with:
          node-version: latest
          registry-url: https://registry.npmjs.org/

      - name: Cache node modules
        if: steps.pr.outputs.skip != 'true'
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        if: steps.pr.outputs.skip != 'true'
        run: npm ci

      - name: Install rollup binary
        if: steps.pr.outputs.skip != 'true'
        run: npm i -D @rollup/rollup-linux-x64-gnu

      - name: Run test:docs
        if: steps.pr.outputs.skip != 'true'
        run: npm run test:docs

      - name: Deploy test docs to GitHub Pages
        if: steps.pr.outputs.skip != 'true'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.RELEASE_TOKEN }}
          publish_dir: ./docs/test
          destination_dir: ${{ github.sha }}
          keep_files: true

      - name: Wait for Storybook and run tests
        if: steps.pr.outputs.skip != 'true'
        run: |
          npx wait-on https://evlmaistrenko.github.io/js-lib-sandbox/${{ github.sha }}/storybook --timeout 60000 --log
          npm test

  release-please:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.RELEASE_TOKEN }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
